### ISSUE TITLE
Request for Reconsideration: Submission of "cdk-dynamodb-search" Construct

### ISSUE THREAD

**Issue by soflass1293** [cdklabs/construct-hub#1403]
Dear Construct Hub Team,

I hope this email finds you well. I am writing to request a reconsideration of my submission titled "cdk-dynamodb-search" on Construct Hub. Despite my efforts to ensure that the construct meets all the necessary requirements and quality standards, I understand that it was not accepted for inclusion on the platform.

[The construct GitHub link](https://github.com/soflass1293/cdk-dynamodb-meilisearch-typescript)

I would appreciate it if you could provide specific feedback on why the submission was not accepted. Understanding any shortcomings will allow me to address them effectively and ensure that the construct aligns with Construct Hub's criteria.

Additionally, I believe that "cdk-dynamodb-search" offers valuable functionality and fills a gap in the available constructs. It has been developed with meticulous attention to detail and adheres to best practices in construct development.

I am committed to enhancing the construct further, if necessary, to meet the platform's standards. Your guidance in this matter would be immensely valuable.

Thank you for considering my request for reconsideration. I look forward to your feedback and the opportunity to contribute to the Construct Hub community.

Sincerely.

**Comment by truggeriaws** [comment]
@soflass1293 - after review, your construct is not being ingested because the version in your [`package.json` file](https://github.com/soflass1293/cdk-dynamodb-meilisearch-typescript/blob/fbda9b37d42bebee9124c6be99f63508e709c17e/package.json#L4) and [`.jsii` file](https://github.com/soflass1293/cdk-dynamodb-meilisearch-typescript/blob/fbda9b37d42bebee9124c6be99f63508e709c17e/.jsii#L3800) do not match (`1.0.0` vs `0.1.18`). If you submit an update to npmjs with matching versions, constructs.dev will reevaluate your package on our next successful ingestion.

**Comment by soflass1293** [comment]
@truggeriaws thank you for your response
