### ISSUE TITLE
New packages may not be ingested

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub#203]
Our discovery function polls `npmjs.com` for new packages. Once a package is detected, the transliterator tries to `npm install` this package from the dedicated CodeArtifact repository that mirrors `npmjs.com`. 

Occasionally, a delay may occur between the time a package is available on `npmjs.com` and CodeArtifact. This means that we might be dropping new packages as they come in.

We need to make sure we have sufficient retry mechanism in-place that mitigate this delay.

**Comment by iliapolo** [comment]
Sharing some data as to the severity of this issue. 

In the past 3 days, the ingestion function received 126 packages:

<img width="1010" alt="Screen Shot 2021-07-21 at 5 49 04 PM" src="https://user-images.githubusercontent.com/1428812/126509265-978de254-7c47-43ed-9cfe-3dc282fa627c.png">

In the same time period, the transliterator successfully processed 121 packages:

<img width="1027" alt="Screen Shot 2021-07-21 at 5 50 45 PM" src="https://user-images.githubusercontent.com/1428812/126509503-12c5eedc-0e1d-4c58-bc9c-918a3b7bca12.png">

This means that in total we dropped 5 packages. Looking at the transliteration errors during this time:

<img width="1021" alt="Screen Shot 2021-07-21 at 5 51 58 PM" src="https://user-images.githubusercontent.com/1428812/126509715-10214c35-7a91-400b-a758-5900d83235c5.png">

We see that there are 15 errors - which makes sense since 15 = 5 (packages) * 3 (retries).

Looking at the errors themselves, none of them seem to stem from the delay this issue speaks of. The errors I observed are:

- no space left on device
-  Type '@epilot/cdk-constructs.HttpApiProps' not found in assembly @epilot/cdk-constructs

I'll be looking into those errors regardless, but as far as concern from the CA delay, we are probably OK for now. 
Having said that, we currently only rely on the built in lambda retry policy, which feels too fragile, and we should introduce a more aggressive retry mechanism (queue, step function..).
