### ISSUE TITLE
Not enough cards in the search results page

### ISSUE THREAD

**Issue by eladb** [cdklabs/construct-hub#270]
It should be possible to fit more cards in the results page:

![Screen Shot 2021-08-03 at 20 46 50](https://user-images.githubusercontent.com/598796/128062049-808068c8-03cc-4ac3-bf03-0278ce1174b9.png)

**Comment by gabewomble** [comment]
This has to do with having a responsive grid with paginated results - One option would be to limit to 20 or 40 results per page so that we can display the following items per column depending on viewport: 1, 2, 4, 5. My suggestion isn't by any means the only solution, but having a variable amount of rows based on viewport width is a constraining factor in filling out the last column of results

**Comment by addihorowitz** [comment]
We're changing the UX/UI design of the results page. Therefore I'm closing this ticket.
