### ISSUE TITLE
ECS Service Extensions not listed

### ISSUE THREAD

**Issue by upparekh** [cdklabs/construct-hub#525]
Hi,

We'd like to have the [ECS CDK service extensions](https://www.npmjs.com/package/@aws-cdk-containers/ecs-service-extensions) added to the Construct Hub. Currently it doesn't show up on searching.

**Comment by Chriscbr** [comment]
I believe the reason the package is not appearing is because it does not include a `.jsii` file. This usually a sign that the library wasn't compiled using JSII, but in this case it seems unlikely since it's within the AWS CDK repo. I imagine this is a configuration issue with how the package is configured as part of the monorepo.
