### ISSUE TITLE
crow-api not listed

### ISSUE THREAD

**Issue by thomasstep** [cdklabs/construct-hub#640]
[GitHub repo](https://github.com/thomasstep/crow-api)
[npm package](https://www.npmjs.com/package/crow-api)
[PyPI package](https://pypi.org/project/crow-api.core/)

I believe I added everything needed based on the [contribute page](https://constructs.dev/contribute). It is also compiled with JSII. Would someone mind giving me any insight into why it is not being listed?

**Comment by Chriscbr** [comment]
Hi @thomasstep ! It appears your package is not currently being listed since it does not include a `.jsii` file (if you try running `npm install crow-api` in a new directory, and look inside the `node_modules`, it's nowhere to be found).

I did notice your GitHub repo has a `.jsii` file and the `.npmignore` includes `!.jsii` so I wasn't sure why it wasn't being included. But I did a little investigative work and I realized the reason is that you are specifying both `.npmignore` and a `files` field in your `package.json`. When the `files` field is used, it will takes precedence over `.npmignore`. So you should either add `.jsii` to `files` or remove `files` from your `package.json`. 👍 

I'll close this out as resolved, but if you run into other problems, please feel free to create another issue.

**Comment by thomasstep** [comment]
@Chriscbr That did the trick. Thank you!
