### ISSUE TITLE
Package Not Appearing on Site

### ISSUE THREAD

**Issue by GEMISIS** [cdklabs/construct-hub#850]
Recently updated https://www.npmjs.com/package/discord-bot-cdk-construct to build with JSII. Confirmed that
- the .jsii file is included (as well as the JSII packaged exports)
- `awscdk` is a keyword for the project
- It's licensed under the MIT license (which appears on the NPM page too)

Even after more than a half hour, I'm not seeing it appear on the site.

**Comment by Chriscbr** [comment]
Hi @GEMISIS! Thanks for reaching out.

I did some investigation, and it looks like JSII was set up correctly and all of the licensing is correct - but our system is rejecting the package because the version of the package listed in the `.jsii` metadata file doesn't match the version listed in `package.json`. Try bumping your version in `package.json` and _then_ running jsii, and I believe then your construct library should appear on Construct Hub! 😄

**Comment by GEMISIS** [comment]
Ah, cool, looks like it's resolved now! ^_^
